<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>3.0.0</Version>
    <PackageOutputPath>../../Packages</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.Security.Domain" Version="3.0.0" />
    <PackageReference Include="Core.Security.Encryption" Version="3.0.0" />
    <PackageReference Include="Core.Security.Extensions" Version="3.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Security.Domain\Core.Security.Domain.csproj" />
  </ItemGroup>

</Project>
