<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>3.1.7</Version>
    <PackageOutputPath>../../Packages</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.Domain" Version="3.0.2" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>

</Project>
